name: Docs

on:
    push:
        branches: [main]

jobs:
    docs:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3.0.2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3.4.1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run docs
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3.8.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
                  publish_branch: gh-pages
